import type {ComparableProduct} from "./types";

export const demoProducts: ComparableProduct[] = [
    {
        id: "olive-oil-extra",
        name: "Aceite de oliva virgen extra",
        unit: "Botella 1 L",
        category: "oils",
        categoryLabel: "Aceites",
        icon: "oil",
        savingsPercent: 18,
        prices: [
            {storeId: "mercaval", storeName: "Mercaval", price: 7.45, unitPrice: "7,45 €/L", status: "available", updatedAtLabel: "Actualizado hoy"},
            {storeId: "aldi-sol", storeName: "Aldi Sol", price: 7.75, unitPrice: "7,75 €/L", status: "available", updatedAtLabel: "Actualizado hoy"},
            {storeId: "bonpreu", storeName: "BonPreu", price: 8.10, unitPrice: "8,10 €/L", status: "available", updatedAtLabel: "Hace 2 h"},
            {storeId: "carretera", storeName: "Carretera", price: 8.39, unitPrice: "8,39 €/L", status: "stale", updatedAtLabel: "Hace 3 días"},
            {storeId: "condis-plus", storeName: "Condis Plus", price: null, unitPrice: "—", status: "unavailable", updatedAtLabel: "Sin stock"},
        ],
        history: [
            {month: "Dic", price: 8.95},
            {month: "Ene", price: 8.65},
            {month: "Feb", price: 8.20},
            {month: "Mar", price: 7.95},
            {month: "Abr", price: 7.70},
            {month: "May", price: 7.45},
        ],
    },
    {
        id: "whole-milk",
        name: "Leche entera",
        unit: "Brick 1 L",
        category: "dairy",
        categoryLabel: "Lácteos",
        icon: "milk",
        savingsPercent: 12,
        prices: [
            {storeId: "aldi-sol", storeName: "Aldi Sol", price: 0.92, unitPrice: "0,92 €/L", status: "available", updatedAtLabel: "Actualizado hoy"},
            {storeId: "mercaval", storeName: "Mercaval", price: 0.98, unitPrice: "0,98 €/L", status: "available", updatedAtLabel: "Actualizado hoy"},
            {storeId: "condis-plus", storeName: "Condis Plus", price: 1.05, unitPrice: "1,05 €/L", status: "available", updatedAtLabel: "Hace 1 h"},
            {storeId: "bonpreu", storeName: "BonPreu", price: 1.09, unitPrice: "1,09 €/L", status: "available", updatedAtLabel: "Actualizado hoy"},
            {storeId: "carretera", storeName: "Carretera", price: 1.15, unitPrice: "1,15 €/L", status: "stale", updatedAtLabel: "Hace 4 días"},
        ],
        history: [
            {month: "Dic", price: 1.09},
            {month: "Ene", price: 1.04},
            {month: "Feb", price: 1.02},
            {month: "Mar", price: 0.99},
            {month: "Abr", price: 0.95},
            {month: "May", price: 0.92},
        ],
    },
    {
        id: "round-rice",
        name: "Arroz redondo",
        unit: "Paquete 1 kg",
        category: "cereals",
        categoryLabel: "Cereales",
        icon: "rice",
        savingsPercent: 9,
        prices: [
            {storeId: "bonpreu", storeName: "BonPreu", price: 1.28, unitPrice: "1,28 €/kg", status: "available", updatedAtLabel: "Actualizado hoy"},
            {storeId: "mercaval", storeName: "Mercaval", price: 1.35, unitPrice: "1,35 €/kg", status: "available", updatedAtLabel: "Actualizado hoy"},
            {storeId: "carretera", storeName: "Carretera", price: 1.41, unitPrice: "1,41 €/kg", status: "available", updatedAtLabel: "Hace 2 h"},
            {storeId: "aldi-sol", storeName: "Aldi Sol", price: 1.49, unitPrice: "1,49 €/kg", status: "available", updatedAtLabel: "Actualizado hoy"},
            {storeId: "condis-plus", storeName: "Condis Plus", price: null, unitPrice: "—", status: "unavailable", updatedAtLabel: "Sin stock"},
        ],
        history: [
            {month: "Dic", price: 1.42},
            {month: "Ene", price: 1.39},
            {month: "Feb", price: 1.36},
            {month: "Mar", price: 1.34},
            {month: "Abr", price: 1.31},
            {month: "May", price: 1.28},
        ],
    },
    {
        id: "natural-yogurt",
        name: "Yogur natural",
        unit: "Pack 4 x 125 g",
        category: "dairy",
        categoryLabel: "Lácteos",
        icon: "yogurt",
        savingsPercent: 15,
        prices: [
            {storeId: "mercaval", storeName: "Mercaval", price: 1.36, unitPrice: "2,72 €/kg", status: "available", updatedAtLabel: "Actualizado hoy"},
            {storeId: "condis-plus", storeName: "Condis Plus", price: 1.48, unitPrice: "2,96 €/kg", status: "available", updatedAtLabel: "Hace 30 min"},
            {storeId: "aldi-sol", storeName: "Aldi Sol", price: 1.55, unitPrice: "3,10 €/kg", status: "available", updatedAtLabel: "Actualizado hoy"},
            {storeId: "bonpreu", storeName: "BonPreu", price: 1.62, unitPrice: "3,24 €/kg", status: "available", updatedAtLabel: "Hace 2 h"},
            {storeId: "carretera", storeName: "Carretera", price: 1.68, unitPrice: "3,36 €/kg", status: "stale", updatedAtLabel: "Hace 5 días"},
        ],
        history: [
            {month: "Dic", price: 1.60},
            {month: "Ene", price: 1.57},
            {month: "Feb", price: 1.49},
            {month: "Mar", price: 1.44},
            {month: "Abr", price: 1.39},
            {month: "May", price: 1.36},
        ],
    },
    {
        id: "ground-coffee",
        name: "Café molido suave",
        unit: "Paquete 250 g",
        category: "drinks",
        categoryLabel: "Bebidas",
        icon: "coffee",
        savingsPercent: 21,
        prices: [
            {storeId: "carretera", storeName: "Carretera", price: 2.89, unitPrice: "11,56 €/kg", status: "available", updatedAtLabel: "Actualizado hoy"},
            {storeId: "mercaval", storeName: "Mercaval", price: 3.10, unitPrice: "12,40 €/kg", status: "available", updatedAtLabel: "Hace 1 h"},
            {storeId: "aldi-sol", storeName: "Aldi Sol", price: 3.24, unitPrice: "12,96 €/kg", status: "available", updatedAtLabel: "Actualizado hoy"},
            {storeId: "bonpreu", storeName: "BonPreu", price: 3.55, unitPrice: "14,20 €/kg", status: "available", updatedAtLabel: "Hace 3 h"},
            {storeId: "condis-plus", storeName: "Condis Plus", price: 3.65, unitPrice: "14,60 €/kg", status: "stale", updatedAtLabel: "Hace 6 días"},
        ],
        history: [
            {month: "Dic", price: 3.66},
            {month: "Ene", price: 3.49},
            {month: "Feb", price: 3.35},
            {month: "Mar", price: 3.20},
            {month: "Abr", price: 3.02},
            {month: "May", price: 2.89},
        ],
    },
];
